#  scraping
name: scrape_health

# Controls when the action will run.
# on:
#   schedule:
#     - cron: '* * * * *' # every minute https://crontab.guru/#*_0_*_*_*
    
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  autoscrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Load repo and install R
    # docker run -d -p 4445:4444 selenium/standalone-chrome
    steps:
    - uses: docker://selenium/standalone-chrome
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages("tidyverse")'
        R -e 'install.packages("rvest")'
        R -e 'install.packages("RSelenium")'
    # Run R script
    - name: Scrape
      run: Rscript scrape_health.R

    # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name github-actions
        git config --local user.email "actions@github.com"
        git add outputs/*
        git commit -am "GH ACTION Autorun $(date)"
        git push origin master
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
