#  scraping
name: scrape_health

# Controls when the action will run.
# on:
#   schedule:
#     - cron: '* * * * *' # every minute https://crontab.guru/#*_0_*_*_*
    
    # "0 9 * * 0-6" every day at 9am
    
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  autoscrape:
  # Declare I want a selenium container as a service
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - "4445:4444"
      # And also tidyverse?
      tidyverse:
        image: rocker/tidyverse
    # The type of VM that the job will run on
    runs-on: ubuntu-latest

    # Load repo and install R
    # docker run -d -p 4445:4444 selenium/standalone-chrome
    steps:
    # - uses: docker://selenium/standalone-chrome
    - uses: actions/checkout@master
    #- uses: r-lib/actions/setup-r@master
    # - name: Change mode
    #   run: 'chmod 777 "/usr/local/lib/R/site-library"'
    # Set-up R
    - name: Install packages # https://github.com/r-lib/remotes/issues/536
      run: |
       uses: r-lib/actions/setup-r@v1
       Rscript -e 'install.packages("RSelenium")'      
#       Rscript -e 'install.packages("RSelenium", lib = "/usr/local/lib/R/site-library")'
      # Rscript -e 'user_lib <- Sys.getenv("R_LIBS_USER"); message("user_lib = ", user_lib); install.packages("RSelenium", lib = user_lib)'
#R -e 'devtools::install_cran("RSelenium")'
#        docker run rocker/tidyverse
 
      
# sudo Rscript -e 'user_lib <- Sys.getenv("R_LIBS_USER"); message("user_lib = ", user_lib); install.packages("RSelenium", force = FALSE, upgrade = TRUE, lib = user_lib)'
#        R -e 'install.packages("tidyverse")'
#        R -e 'install.packages("rvest")'
        
    # Run R script
    - name: Scrape
      run: Rscript 'code/scrape_health.R'

    # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name github-actions
        git config --local user.email "actions@github.com"
        git add outputs/*
        git commit -am "GH ACTION Autorun $(date)"
        git push origin master
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
