#  scraping
name: scrape_health

# Controls when the action will run.
# on:
#   schedule:
#     - cron: '* * * * *' # every minute https://crontab.guru/#*_0_*_*_*
    
    # "0 9 * * 0-6" every day at 9am
    
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  scrape_health:
      # The type of VM that the job will run on
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse
  # Declare I want a selenium container as a service
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - "4445:4444"

    steps:
     - uses: actions/checkout@master
    # Run R script
     - name: Scrape
        run: Rscript 'code/scrape_health.R'

    # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name github-actions
        git config --local user.email "actions@github.com"
        git add outputs/*
        git commit -am "GH ACTION Autorun $(date)"
        git push origin master
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions


    # - name: Run Selenium container
    #   run: docker run -d -p 4445:4444 selenium/standalone-chrome
    # - name: Run R container
    #   run: |
    #     docker run -d -p rocker/tidyverse
        # Rscript 'code/scrape_health.R'
    
#  - uses: r-lib/actions/setup-r@v1
    #- uses: r-lib/actions/setup-r@master
    # Set-up R
    # - name: Install packages
    #   run: |
    #     Rscript -e 'install.packages("RSelenium")'
    #     Rscript -e 'install.packages("rvest")'
#       Rscript -e 'install.packages("RSelenium", lib = "/usr/local/lib/R/site-library")'
      # Rscript -e 'user_lib <- Sys.getenv("R_LIBS_USER"); message("user_lib = ", user_lib); install.packages("RSelenium", lib = user_lib)'
#R -e 'devtools::install_cran("RSelenium")'
#        docker run rocker/tidyverse
 
 